# vcache
enable_gpu_vram_pool: true
use_vram_metadata_server: true
local_hostname: "192.168.1.86:12346"

# Token chunking configuration
chunk_size: 256  

# GPUVRAMPoolManager
max_gpu_vram_metadata_size: 10000

# MooncakeStorageBackend
metadata_server: "http://192.168.1.86:8080/metadata"
global_segment_size: 631242752  # B
local_buffer_size: 631242752    # B
master_server_address: "192.168.1.86:50051"
protocol: "tcp"

# GPUVRAMSegmentManager
gpu_vram_segment_size_mb: 256
enable_gpu_vram_segments: true

# VRAMMetadataIPCClient
vram_metadata_ipc_address: "192.168.1.86"
vram_metadata_ipc_port: 9091
vram_metadata_ipc_retry_count: 3

# TransferEngineManager
transfer_engine_type: "nvlink"
gpu_id: 1

# nvlink_transfer_engine
max_concurrent_transfers: 8
transfer_timeout_sec: 30

# mooncake_transfer_engine
local_hostname_TE: "192.168.1.86:13246"
protocol_TE: "nvlink"
device_name: ""
