enable_gpu_vram_pool: true
use_vram_metadata_server: true

# GPUVRAMPoolManager
max_gpu_vram_metadata_size: 10000
local_hostname: "192.168.1.86:12346"
local_hostname_TE: "192.168.1.86:13246"
metadata_server: "http://192.168.1.86:8080/metadata"
protocol: "tcp"
protocol_TE: "nvlink"
device_name: ""

# MooncakeStorageBackend
mc_metadata_server: "http://192.168.1.86:8080/metadata"
global_segment_size: 631242752  # B
local_buffer_size: 631242752    # B
master_server_address: "192.168.1.86:50051"

gpu_vram_segment_size_mb: 256
enable_gpu_vram_segments: true

vram_metadata_ipc_address: "192.168.1.86"
vram_metadata_ipc_port: 9091